"""add_staging_passwords_table

Revision ID: 8dfea8e39bfe
Revises: 0e81d0b569a8
Create Date: 2026-07-21 22:05:16.256683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8dfea8e39bfe'
down_revision: Union[str, Sequence[str], None] = '0e81d0b569a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staging_passwords',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_staging_password_company', 'staging_passwords', ['company_id'], unique=False)
    op.create_index(op.f('ix_staging_passwords_company_id'), 'staging_passwords', ['company_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_staging_passwords_company_id'), table_name='staging_passwords')
    op.drop_index('idx_staging_password_company', table_name='staging_passwords')
    op.drop_table('staging_passwords')
    # ### end Alembic commands ###
