"""add_safety_integrations_table

Revision ID: b7d1a2c3f8e4
Revises: 8dfea8e39bfe
Create Date: 2026-07-27 23:22:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7d1a2c3f8e4'
down_revision: Union[str, Sequence[str], None] = '8dfea8e39bfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('safety_integrations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tax_id', sa.String(length=14), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('watched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True, server_default='true'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tax_id', 'company_id', name='unique_safety_integration_per_company')
    )
    op.create_index('idx_safety_integrations_lookup', 'safety_integrations', ['tax_id', 'company_id'], unique=False)
    op.create_index(op.f('ix_safety_integrations_tax_id'), 'safety_integrations', ['tax_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_safety_integrations_tax_id'), table_name='safety_integrations')
    op.drop_index('idx_safety_integrations_lookup', table_name='safety_integrations')
    op.drop_table('safety_integrations')
    # ### end Alembic commands ###
