"""add_user_fcm_tokens

Revision ID: d604102778d8
Revises: 
Create Date: 2026-07-19 00:11:09.339678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd604102778d8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_fcm_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('fcm_token', sa.String(length=255), nullable=False),
    sa.Column('device_os', sa.String(length=10), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fcm_token_user_id', 'user_fcm_tokens', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_fcm_tokens_fcm_token'), 'user_fcm_tokens', ['fcm_token'], unique=True)
    op.drop_index(op.f('idx_company_fts_search'), table_name='companies', postgresql_using='gin')
    op.create_index(op.f('ix_companies_unit_code'), 'companies', ['unit_code'], unique=False)
    op.alter_column('users', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_companies_unit_code'), table_name='companies')
    op.create_index(op.f('idx_company_fts_search'), 'companies', [sa.literal_column("to_tsvector('portuguese'::regconfig, (name::text || ' '::text) || COALESCE(branch_name, ''::character varying)::text)")], unique=False, postgresql_using='gin')
    op.drop_index(op.f('ix_user_fcm_tokens_fcm_token'), table_name='user_fcm_tokens')
    op.drop_index('idx_fcm_token_user_id', table_name='user_fcm_tokens')
    op.drop_table('user_fcm_tokens')
    # ### end Alembic commands ###
