"""initial_migration

Revision ID: d8ae919842f6
Revises: 
Create Date: 2026-07-29 16:21:12.470125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd8ae919842f6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    
    op.execute("CREATE EXTENSION IF NOT EXISTS unaccent SCHEMA extensions;")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm SCHEMA extensions;")
    op.execute("""
        CREATE OR REPLACE FUNCTION f_unaccent(text)
          RETURNS text AS
        $BODY$
          SELECT extensions.unaccent($1);
        $BODY$
          LANGUAGE sql IMMUTABLE;
    """)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allowed_domains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_allowed_domains_lookup', 'allowed_domains', ['domain', 'is_active'], unique=False)
    op.create_index(op.f('ix_allowed_domains_domain'), 'allowed_domains', ['domain'], unique=True)
    op.create_table('companies',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('branch_name', sa.String(length=100), nullable=True),
    sa.Column('unit_code', sa.String(length=50), nullable=True),
    sa.Column('tax_id', sa.String(length=20), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('api_key_hash', sa.String(length=255), nullable=True),
    sa.Column('api_key_prefix', sa.String(length=50), nullable=True),
    sa.Column('api_key_secondary_hash', sa.String(length=255), nullable=True),
    sa.Column('api_key_secondary_prefix', sa.String(length=50), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('address_street', sa.String(length=150), nullable=True),
    sa.Column('address_number', sa.String(length=20), nullable=True),
    sa.Column('address_city', sa.String(length=100), nullable=True),
    sa.Column('address_state', sa.String(length=50), nullable=True),
    sa.Column('address_country', sa.String(length=50), nullable=True),
    sa.Column('address_zip', sa.String(length=20), nullable=True),
    sa.Column('address_lat', sa.Float(), nullable=True),
    sa.Column('address_lng', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tax_id'),
    sa.UniqueConstraint('username')
    )
    op.create_index('idx_company_trgm_search', 'companies', [sa.literal_column("f_unaccent(name || ' ' || COALESCE(branch_name, '')) gin_trgm_ops")], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_companies_api_key_prefix'), 'companies', ['api_key_prefix'], unique=True)
    op.create_index(op.f('ix_companies_api_key_secondary_prefix'), 'companies', ['api_key_secondary_prefix'], unique=True)
    op.create_index(op.f('ix_companies_unit_code'), 'companies', ['unit_code'], unique=False)
    op.create_table('register_requests',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tax_id', sa.String(length=14), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('trusted_device', sa.String(length=100), nullable=True),
    sa.Column('register_step', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_register_requests_tax_id'), 'register_requests', ['tax_id'], unique=True)
    op.create_table('announcements',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('subtitle', sa.String(length=150), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('image_position', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_announcements_active', 'announcements', ['is_active', 'start_at', 'end_at'], unique=False)
    op.create_index('idx_announcements_company', 'announcements', ['company_id'], unique=False)
    op.create_table('companies_users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('company_services',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('icon_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['domain_id'], ['allowed_domains.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_company_services_domain', 'company_services', ['domain_id'], unique=False)
    op.create_index('idx_company_services_ids', 'company_services', ['id'], unique=False)
    op.create_index('idx_company_services_lookup', 'company_services', ['company_id', 'is_active'], unique=False)
    op.create_table('drivers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tax_id', sa.String(length=14), nullable=False),
    sa.Column('driver_license_number', sa.String(length=20), nullable=True),
    sa.Column('driver_license_category', sa.String(length=10), nullable=True),
    sa.Column('driver_license_expiration', sa.Date(), nullable=True),
    sa.Column('validated_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['validated_by'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drivers_tax_id'), 'drivers', ['tax_id'], unique=True)
    op.create_table('safety_integrations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tax_id', sa.String(length=14), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('watched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tax_id', 'company_id', name='unique_safety_integration_per_company')
    )
    op.create_index('idx_safety_integrations_lookup', 'safety_integrations', ['tax_id', 'company_id'], unique=False)
    op.create_index(op.f('ix_safety_integrations_tax_id'), 'safety_integrations', ['tax_id'], unique=False)
    op.create_table('staging_passwords',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_staging_password_company', 'staging_passwords', ['company_id'], unique=False)
    op.create_index(op.f('ix_staging_passwords_company_id'), 'staging_passwords', ['company_id'], unique=True)
    op.create_table('terminals',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('geofence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('appointment_layouts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ticket_layouts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('use_remote_checkin', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trucking_companies',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('trip_layouts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appointments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('terminal_id', sa.BigInteger(), nullable=False),
    sa.Column('ref', sa.String(length=100), nullable=True),
    sa.Column('layout_ref', sa.String(length=50), nullable=True),
    sa.Column('user_tax_id', sa.String(length=14), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('summary', sa.String(length=150), nullable=True),
    sa.Column('license_plate', sa.String(length=10), nullable=True),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('start_tolerance', sa.Integer(), nullable=True),
    sa.Column('end_tolerance', sa.Integer(), nullable=True),
    sa.Column('custom_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_ping_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['terminal_id'], ['terminals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('terminal_id', 'ref', name='unique_appointment_ref_per_company')
    )
    op.create_index('idx_appointment_terminal_ref', 'appointments', ['terminal_id', 'ref'], unique=False)
    op.create_index(op.f('ix_appointments_license_plate'), 'appointments', ['license_plate'], unique=False)
    op.create_index(op.f('ix_appointments_ref'), 'appointments', ['ref'], unique=False)
    op.create_index(op.f('ix_appointments_user_tax_id'), 'appointments', ['user_tax_id'], unique=False)
    op.create_table('appointments_layouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('terminal_id', sa.BigInteger(), nullable=False),
    sa.Column('ref', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('layout', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['terminal_id'], ['terminals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_appointment_layout_lookup', 'appointments_layouts', ['terminal_id', 'ref', 'title'], unique=False)
    op.create_table('tickets_layouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('terminal_id', sa.BigInteger(), nullable=False),
    sa.Column('ref', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('layout', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['terminal_id'], ['terminals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ticket_layout_lookup', 'tickets_layouts', ['terminal_id', 'ref', 'title'], unique=False)
    op.create_table('trips',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('trucking_company_id', sa.BigInteger(), nullable=False),
    sa.Column('ref', sa.String(length=100), nullable=True),
    sa.Column('layout_ref', sa.String(length=50), nullable=True),
    sa.Column('driver_id', sa.BigInteger(), nullable=True),
    sa.Column('license_plate', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('summary', sa.String(length=150), nullable=True),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('start_tolerance', sa.Integer(), nullable=True),
    sa.Column('end_tolerance', sa.Integer(), nullable=True),
    sa.Column('custom_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('origin_street', sa.String(length=150), nullable=True),
    sa.Column('origin_number', sa.String(length=20), nullable=True),
    sa.Column('origin_city', sa.String(length=100), nullable=True),
    sa.Column('origin_state', sa.String(length=50), nullable=True),
    sa.Column('origin_country', sa.String(length=50), nullable=True),
    sa.Column('origin_zip', sa.String(length=20), nullable=True),
    sa.Column('origin_lat', sa.Float(), nullable=True),
    sa.Column('origin_lng', sa.Float(), nullable=True),
    sa.Column('destiny_street', sa.String(length=150), nullable=True),
    sa.Column('destiny_number', sa.String(length=20), nullable=True),
    sa.Column('destiny_city', sa.String(length=100), nullable=True),
    sa.Column('destiny_state', sa.String(length=50), nullable=True),
    sa.Column('destiny_country', sa.String(length=50), nullable=True),
    sa.Column('destiny_zip', sa.String(length=20), nullable=True),
    sa.Column('destiny_lat', sa.Float(), nullable=True),
    sa.Column('destiny_lng', sa.Float(), nullable=True),
    sa.Column('from_location', sa.String(length=100), nullable=True),
    sa.Column('to_location', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['trucking_company_id'], ['trucking_companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trucking_company_id', 'ref', name='unique_trip_ref_per_company')
    )
    op.create_index('idx_trip_company_ref', 'trips', ['trucking_company_id', 'ref'], unique=False)
    op.create_index(op.f('ix_trips_license_plate'), 'trips', ['license_plate'], unique=False)
    op.create_index(op.f('ix_trips_ref'), 'trips', ['ref'], unique=False)
    op.create_table('trips_layouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trucking_company_id', sa.BigInteger(), nullable=False),
    sa.Column('ref', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('layout', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['trucking_company_id'], ['trucking_companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_trip_layout_lookup', 'trips_layouts', ['trucking_company_id', 'ref', 'title'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tax_id', sa.String(length=14), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('validated_device', sa.String(length=100), nullable=True),
    sa.Column('driver_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('tax_id')
    )
    op.create_table('announcements_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('announcement_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('company_user_id', sa.BigInteger(), nullable=True),
    sa.Column('event', sa.Enum('CREATED', 'UPDATED', 'DELETED', 'VIEWED', name='announcement_event'), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_user_id'], ['companies_users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appointments_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('appointment_id', sa.BigInteger(), nullable=False),
    sa.Column('event', sa.Enum('CREATED', 'UPDATED', 'DELETED', 'TICKET_CREATED', 'TICKET_UPDATED', 'TICKET_DELETED', 'TERMINAL_PING', 'NOTIFICATION_SENT', 'AUTO_DEACTIVATED', 'CHECKIN_CANCELLED', 'VIEWED', 'CLICKED', name='appointment_event'), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tickets',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('appointment_id', sa.BigInteger(), nullable=False),
    sa.Column('appointment_ref', sa.String(length=100), nullable=False),
    sa.Column('terminal_id', sa.BigInteger(), nullable=False),
    sa.Column('layout_ref', sa.String(length=50), nullable=True),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['terminal_id'], ['terminals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trips_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('trip_id', sa.BigInteger(), nullable=False),
    sa.Column('event', sa.Enum('CREATED', 'UPDATED', 'DELETED', 'VIEWED', 'CLICKED', name='trip_event'), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_fcm_tokens',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('fcm_token', sa.String(length=255), nullable=False),
    sa.Column('device_os', sa.String(length=10), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fcm_token_user_id', 'user_fcm_tokens', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_fcm_tokens_fcm_token'), 'user_fcm_tokens', ['fcm_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_fcm_tokens_fcm_token'), table_name='user_fcm_tokens')
    op.drop_index('idx_fcm_token_user_id', table_name='user_fcm_tokens')
    op.drop_table('user_fcm_tokens')
    op.drop_table('trips_logs')
    op.drop_table('tickets')
    op.drop_table('appointments_logs')
    op.drop_table('announcements_logs')
    op.drop_table('users')
    op.drop_index('idx_trip_layout_lookup', table_name='trips_layouts')
    op.drop_table('trips_layouts')
    op.drop_index(op.f('ix_trips_ref'), table_name='trips')
    op.drop_index(op.f('ix_trips_license_plate'), table_name='trips')
    op.drop_index('idx_trip_company_ref', table_name='trips')
    op.drop_table('trips')
    op.drop_index('idx_ticket_layout_lookup', table_name='tickets_layouts')
    op.drop_table('tickets_layouts')
    op.drop_index('idx_appointment_layout_lookup', table_name='appointments_layouts')
    op.drop_table('appointments_layouts')
    op.drop_index(op.f('ix_appointments_user_tax_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_ref'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_license_plate'), table_name='appointments')
    op.drop_index('idx_appointment_terminal_ref', table_name='appointments')
    op.drop_table('appointments')
    op.drop_table('trucking_companies')
    op.drop_table('terminals')
    op.drop_index(op.f('ix_staging_passwords_company_id'), table_name='staging_passwords')
    op.drop_index('idx_staging_password_company', table_name='staging_passwords')
    op.drop_table('staging_passwords')
    op.drop_index(op.f('ix_safety_integrations_tax_id'), table_name='safety_integrations')
    op.drop_index('idx_safety_integrations_lookup', table_name='safety_integrations')
    op.drop_table('safety_integrations')
    op.drop_index(op.f('ix_drivers_tax_id'), table_name='drivers')
    op.drop_table('drivers')
    op.drop_index('idx_company_services_lookup', table_name='company_services')
    op.drop_index('idx_company_services_ids', table_name='company_services')
    op.drop_index('idx_company_services_domain', table_name='company_services')
    op.drop_table('company_services')
    op.drop_table('companies_users')
    op.drop_index('idx_announcements_company', table_name='announcements')
    op.drop_index('idx_announcements_active', table_name='announcements')
    op.drop_table('announcements')
    op.drop_index(op.f('ix_register_requests_tax_id'), table_name='register_requests')
    op.drop_table('register_requests')
    op.drop_index(op.f('ix_companies_unit_code'), table_name='companies')
    op.drop_index(op.f('ix_companies_api_key_secondary_prefix'), table_name='companies')
    op.drop_index(op.f('ix_companies_api_key_prefix'), table_name='companies')
    op.drop_index('idx_company_trgm_search', table_name='companies', postgresql_using='gin')
    op.drop_table('companies')
    op.drop_index(op.f('ix_allowed_domains_domain'), table_name='allowed_domains')
    op.drop_index('idx_allowed_domains_lookup', table_name='allowed_domains')
    op.drop_table('allowed_domains')
    # ### end Alembic commands ###
